import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { MultiAgentDslGeneratedModule, MultiAgentDslGeneratedSharedModule } from './generated/module.js';
import { MultiAgentDslValidator, registerValidationChecks } from './multi-agent-dsl-validator.js';
import { MultiAgentDslScopeProvider } from './multi-agent-dsl-scope-provider.js';
import { MultiAgentDslCompletionProvider } from './multi-agent-dsl-completion-provider.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MultiAgentDslAddedServices = {
    validation: {
        MultiAgentDslValidator: MultiAgentDslValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MultiAgentDslServices = LangiumServices & MultiAgentDslAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MultiAgentDslModule: Module<MultiAgentDslServices, PartialLangiumServices & MultiAgentDslAddedServices> = {
    references: {
        ScopeProvider: (services) => new MultiAgentDslScopeProvider(services)
    },
    validation: {
        MultiAgentDslValidator: () => new MultiAgentDslValidator()
    },
    lsp: {
        CompletionProvider: (services) => new MultiAgentDslCompletionProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMultiAgentDslServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    MultiAgentDsl: MultiAgentDslServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MultiAgentDslGeneratedSharedModule
    );
    const MultiAgentDsl = inject(
        createDefaultModule({ shared }),
        MultiAgentDslGeneratedModule,
        MultiAgentDslModule
    );
    shared.ServiceRegistry.register(MultiAgentDsl);
    registerValidationChecks(MultiAgentDsl);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, MultiAgentDsl };
}
